server:
  max-http-header-size: 10000
  port: 8503
  servlet:
    context-path: /smt-log

jdb:
  orm:
    filepath: jdb-orm.conf.xml
    data-source-close-method-name: close

# 指定该服务要注册进指定url的服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.252:8501/eureka/

smt:
  parent:
    code:
      filter:
        cors:
          access-control-allow-methods: GET,POST,PUT,DELETE
          access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, _log, token
          access-control-max-age: 1800
        log:
          enable: false
        token:
          ignore-url-patterns:
          - /log/add_

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://192.168.1.222:1433;DatabaseName=SMT_ALL
    username: sa
    password: root
  application:
    name: smt-log