server:
  max-http-header-size: 10000
  port: 8503
  servlet:
    context-path: /smt-log

jdb:
  orm:
    filepath: jdb-orm.conf.xml
    data-source-close-method-name: close

# 指定该服务要注册进指定url的服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.111:8501/eureka/

smt:
  parent:
    code:
      filter:
        license:
          public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDhd/m68HBmatodUHbCcbsmIBR5e4u2J5trHCQcoeOl6/iUnMBELa2kk7BzBbR4sOWknLJLr8MN5JpmkSD1BBhMQxP1H+cTxf3BcdY3ZcsWudEXKOfPeEROexiwqBD9kqSHBFZY1zbV2+2IKV1Qmp3bTZHAW508ersXumL4JQKc6wIDAQAB
        cors:
          access-control-allow-methods: GET,POST,PUT,DELETE
          access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, _log, token
          access-control-max-age: 1800
        log:
          enable: false
        token:
          ignore-url-patterns:
          - /log/add_

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://192.168.1.111:1433;DatabaseName=SMT_LOG
    username: sa
    password: 123_abc
  application:
    name: smt-log